services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: redis_api_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: studentdb
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d studentdb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:alpine
    container_name: redis_api_cache
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # FastAPI Web Application
  api:
    build: ./api
    container_name: redis_api_app
    restart: always
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/studentdb
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Python Client
  client:
    build: ./client
    container_name: redis_api_client
    restart: always
    volumes:
      - ./client:/app
    command: tail -f /dev/null
    depends_on:
      - api
      - redis
      - db
