services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_server
    ports:
      - "5672:5672" # RabbitMQ port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # We use the same image for both client examples
  python-client:
    build: .
    volumes:
      - .:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: tail -f /dev/null # Keeps the container running for manual execution
