services:
  haproxy-master:
    build: .
    container_name: haproxy_master
    cap_add:
      # Capabilities Add: se utiliza para otorgar capacidades (capabilities) específicas del kernel de Linux a un contenedor, sin necesidad de darle acceso total de superusuario
      - NET_ADMIN # Permite configurar interfaces de red, IPTables o ruteo.
      - NET_BROADCAST # Permite enviar paquetes de broadcast, necesario para que Keepalived anuncie la VIP.
      - NET_RAW # Permite manejos internos de RED
    volumes:
      - ./haproxy.cfg:/etc/haproxy/haproxy.cfg:ro
      - ./keepalived-master.conf:/etc/keepalived/keepalived.conf:ro
      - ./check_haproxy.sh:/usr/local/bin/check_haproxy.sh:ro
    networks:
      ha_net:
        ipv4_address: 10.25.0.11
    depends_on:
      - web1
      - web2
      - web3

  haproxy-backup:
    build: .
    container_name: haproxy_backup
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    volumes:
      - ./haproxy.cfg:/etc/haproxy/haproxy.cfg:ro
      - ./keepalived-backup.conf:/etc/keepalived/keepalived.conf:ro
      - ./check_haproxy.sh:/usr/local/bin/check_haproxy.sh:ro
    networks:
      ha_net:
        ipv4_address: 10.25.0.12
    depends_on:
      - web1
      - web2
      - web3

  web1:
    image: alpine:latest
    container_name: web1_ha
    hostname: web1_ha
    command: >
      sh -c "apk add --no-cache apache2 && mkdir -p /run/apache2 && INSTANCE_HOSTNAME=$$(hostname) && echo \"<html> <body style='font-family: sans-serif; text-align: center;'>
          <h1>Alpine Linux HA funcionando!</h1>
          <p>Instancia: <b>$$INSTANCE_HOSTNAME</b></p>
      </body> </html>\" > /var/www/localhost/htdocs/index.html && httpd -D FOREGROUND"
    networks:
      - ha_net

  web2:
    image: alpine:latest
    container_name: web2_ha
    hostname: web2_ha
    command: >
      sh -c "apk add --no-cache apache2 && mkdir -p /run/apache2 && INSTANCE_HOSTNAME=$$(hostname) && echo \"<html> <body style='font-family: sans-serif; text-align: center;'>
          <h1>Alpine Linux HA funcionando!</h1>
          <p>Instancia: <b>$$INSTANCE_HOSTNAME</b></p>
      </body> </html>\" > /var/www/localhost/htdocs/index.html && httpd -D FOREGROUND"
    networks:
      - ha_net

  web3:
    image: alpine:latest
    container_name: web3_ha
    hostname: web3_ha
    command: >
      sh -c "apk add --no-cache apache2 && mkdir -p /run/apache2 && INSTANCE_HOSTNAME=$$(hostname) && echo \"<html> <body style='font-family: sans-serif; text-align: center;'>
          <h1>Alpine Linux HA funcionando!</h1>
          <p>Instancia: <b>$$INSTANCE_HOSTNAME</b></p>
      </body> </html>\" > /var/www/localhost/htdocs/index.html && httpd -D FOREGROUND"
    networks:
      - ha_net

networks:
  ha_net:
    ipam:
      driver: default
      config:
        - subnet: 10.25.0.0/24
