# Monitoreo del estado de salud de HAProxy
vrrp_script check_haproxy {
    script "/usr/local/bin/check_haproxy.sh"  # Ruta del script de verificación
    interval 2                                 # Ejecutar cada 2 segundos
    weight -20                                 # Restar 20 de prioridad si falla, queda por debajo de backup
}

# Configuración del clúster VRRP para la IP flotante
# VRRP (Virtual Router Redundancy Protocol): protocolo de comunicación entre dos o más dispositivos (en este caso, los contenedores HAProxy) con el objetivo de compartir una dirección IP virtual (VIP). 
vrrp_instance VI_1 {
    state MASTER            # Estado inicial deseado
    interface eth0          # Interfaz de red
    virtual_router_id 51    # ID del clúster (debe ser igual en master y backup)
    priority 101            # Prioridad de este nodo (101 > 100)
    advert_int 1            # Frecuencia de anuncios heartbeat en segundos

    # Autenticación entre nodos del clúster
    authentication {
        auth_type PASS              # Autenticacion por texto plano
        auth_pass 1111              # Clave de autenticación
    }

    # Dirección IP virtual (VIP) flotante
    virtual_ipaddress {
        10.25.0.100/24
    }

    # Activar el script de monitoreo
    track_script {
        check_haproxy
    }

    # Ajustes de actualización de tablas ARP en la red
    garp_master_delay 1  # Esperar 1 seg despues de tener el rol de master antes de enviar el primer gratutous ARP
    garp_master_refresh 5 # Cada 5 segundos se envia un gratuitous ARP para anunciar que tiene la VIP
}

# ARP significa Address Resolution Protocol. 
# Es un protocolo que se encarga de mapear direcciones IP a direcciones MAC en una red. 
